# Generated by Django 2.1.7 on 2021-08-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordRoleAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.BigIntegerField()),
                ('emoji_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='discordroleassign',
            unique_together={('role_id', 'emoji_id')},
        ),
    ]
