# Generated by Django 4.1.3 on 2022-11-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('member', 'Member'), ('user', 'User'), ('message', 'Message'), ('voice', 'Voice'), ('reaction', 'Reaction')], max_length=50)),
                ('action', models.CharField(choices=[('update', 'Updated'), ('remove', 'Removed'), ('ban', 'Banned'), ('unban', 'Unbanned'), ('join', 'Joined'), ('leave', 'Left'), ('edit', 'Edited'), ('delete', 'Deleted'), ('stop', 'Stopped'), ('start', 'Started')], max_length=50)),
                ('subject', models.CharField(blank=True, choices=[('nick', 'Nickname'), ('roles', 'Roles'), ('guild_avatar', 'Server Avatar'), ('name', 'Username'), ('discriminator', 'Discriminator'), ('avatar', 'Avatar'), ('content', 'Content'), ('attachments', 'Attachments'), ('self_video', 'Screenshare'), ('self_stream', 'Livestream'), ('channel', 'Channel')], max_length=50)),
                ('user_display_name', models.CharField(max_length=32)),
                ('user_discriminator', models.CharField(max_length=4)),
                ('user_display_avatar', models.URLField()),
                ('user_id', models.PositiveBigIntegerField()),
                ('origin', models.CharField(blank=True, max_length=200)),
                ('before', models.TextField(blank=True, max_length=4096)),
                ('after', models.TextField(blank=True, max_length=4096)),
                ('attachment_message_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
