# Generated by Django 4.1.3 on 2025-10-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordlog',
            name='user_display_name',
            field=models.CharField(max_length=100),
        ),
    ]
